s = set()

i1 = int(input("Enter a Number:"))
s.add(i1)
i2 = int(input("Enter a Number:"))
s.add(i2)
i3 = int(input("Enter a Number:"))
s.add(i3)
i4 = int(input("Enter a Number:"))
s.add(i4)
i5 = int(input("Enter a Number:"))
s.add(i5)
i6 = int(input("Enter a Number:"))
s.add(i6)
i7 = int(input("Enter a Number:"))
s.add(i7)
i8 = int(input("Enter a Number:"))
s.add(i8)

print(s)